SEED_QUESTIONS = [
    {
        "id": "qfb-d1-001",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "Yesterday, I ___ (go) to the store.",
        "corrected_answer": "went",
        "explanation": "The past simple of 'go' is 'went'.",
    },
    {
        "id": "qfb-d1-002",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "She ___ (eat) breakfast at 7 a.m.",
        "corrected_answer": "ate",
        "explanation": "The past simple of 'eat' is 'ate'.",
    },
    {
        "id": "qfb-d1-003",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "They ___ (see) a rainbow after the rain.",
        "corrected_answer": "saw",
        "explanation": "The past simple of 'see' is 'saw'.",
    },
    {
        "id": "qfb-d1-004",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "We ___ (have) a great time last night.",
        "corrected_answer": "had",
        "explanation": "The past simple of 'have' is 'had'.",
    },
    {
        "id": "qfb-d1-005",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "He ___ (make) a sandwich for lunch.",
        "corrected_answer": "made",
        "explanation": "The past simple of 'make' is 'made'.",
    },
    {
        "id": "qfb-d1-006",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "I ___ (take) the bus to work this morning.",
        "corrected_answer": "took",
        "explanation": "The past simple of 'take' is 'took'.",
    },
    {
        "id": "qfb-d1-007",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "My brother ___ (find) my keys under the sofa.",
        "corrected_answer": "found",
        "explanation": "The past simple of 'find' is 'found'.",
    },
    {
        "id": "qfb-d1-008",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "Last weekend, we ___ (buy) a new table.",
        "corrected_answer": "bought",
        "explanation": "The past simple of 'buy' is 'bought'.",
    },
    {
        "id": "qfb-d1-009",
        "exercise_type": "fill_blank",
        "difficulty": 1,
        "prompt": "The child ___ (draw) a picture in class.",
        "corrected_answer": "drew",
        "explanation": "The past simple of 'draw' is 'drew'.",
    },
    {
        "id": "qfb-d2-001",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "By noon, she had already ___ (write) the report.",
        "corrected_answer": "written",
        "explanation": "Past perfect uses had + past participle: 'written'.",
    },
    {
        "id": "qfb-d2-002",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "They have never ___ (drive) on the left side before.",
        "corrected_answer": "driven",
        "explanation": "Present perfect uses have/has + past participle: 'driven'.",
    },
    {
        "id": "qfb-d2-003",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "I had ___ (speak) to her before the meeting started.",
        "corrected_answer": "spoken",
        "explanation": "Past perfect uses the participle 'spoken'.",
    },
    {
        "id": "qfb-d2-004",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "We have ___ (choose) a better option this time.",
        "corrected_answer": "chosen",
        "explanation": "Present perfect requires the participle 'chosen'.",
    },
    {
        "id": "qfb-d2-005",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "He had ___ (break) his phone by accident.",
        "corrected_answer": "broken",
        "explanation": "Use the past participle 'broken' after 'had'.",
    },
    {
        "id": "qfb-d2-006",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "The students have ___ (begin) the exam.",
        "corrected_answer": "begun",
        "explanation": "Present perfect form is 'have begun'.",
    },
    {
        "id": "qfb-d2-007",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "Before dinner, I had ___ (drink) two glasses of water.",
        "corrected_answer": "drunk",
        "explanation": "Past perfect takes 'drunk' as the participle of drink.",
    },
    {
        "id": "qfb-d2-008",
        "exercise_type": "fill_blank",
        "difficulty": 2,
        "prompt": "She has ___ (teach) English for ten years.",
        "corrected_answer": "taught",
        "explanation": "Present perfect uses has + past participle: 'taught'.",
    },
    {
        "id": "qfb-d3-001",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "If I had ___ (know) about the delay, I would have left later.",
        "corrected_answer": "known",
        "explanation": "Third conditional uses had + past participle: 'known'.",
    },
    {
        "id": "qfb-d3-002",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "By the time we arrived, the film had already ___ (begin).",
        "corrected_answer": "begun",
        "explanation": "Past perfect requires the participle 'begun'.",
    },
    {
        "id": "qfb-d3-003",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "She would have ___ (take) the offer if she had heard sooner.",
        "corrected_answer": "taken",
        "explanation": "Would have is followed by the past participle 'taken'.",
    },
    {
        "id": "qfb-d3-004",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "They might have ___ (forget) the address without the map.",
        "corrected_answer": "forgotten",
        "explanation": "Modal perfect uses the participle 'forgotten'.",
    },
    {
        "id": "qfb-d3-005",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "He has ___ (swim) competitively since he was ten.",
        "corrected_answer": "swum",
        "explanation": "Present perfect form is 'has swum'.",
    },
    {
        "id": "qfb-d3-006",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "The letter was ___ (write) in a hurry, so it has mistakes.",
        "corrected_answer": "written",
        "explanation": "Passive voice here needs the participle 'written'.",
    },
    {
        "id": "qfb-d3-007",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "Had they ___ (take) the earlier train, they would have arrived on time.",
        "corrected_answer": "taken",
        "explanation": "Inverted third conditional still uses past participle after 'had'.",
    },
    {
        "id": "qfb-d3-008",
        "exercise_type": "fill_blank",
        "difficulty": 3,
        "prompt": "The contract has been ___ (write) to protect both parties.",
        "corrected_answer": "written",
        "explanation": "Present perfect passive requires 'been' + past participle.",
    },
]
